### PR TITLE
Ensure BTCPayServer 2.0 compatibility

### LINKED ISSUE #169: [Bug]: Error after submitting API Key
### What is your BTCPay Server version?

I'm running BTCPay Server v2.0.3 and Prestashop v8.0

### How did you deploy BTCPay Server?

BTCPay Server is deployed via umbrel 

### What is version of the PrestaShop plugin are you using?

I'm running v6.2.1 of the Prestashop plugin

### What happened?

After submitting the API key, I receive a 500 error. Enabling debug on prestashop returns the error:

An exception has been thrown during the rendering of a template ("Error during GET to https://btcpay.server.com/api/v1/stores/storeID/payment-methods/LightningNetwork. Got response (410): {"code":"unsupported-in-v2","message":"This route isn't supported by BTCPay Server 2.0 and newer. Please update your integration."}").

### How did you encounter this bug?

I submitted the API key and clicked the save button and received a 500 error.

### Relevant log output

```shell
Debugger is returning the error from L198 of `modules/btcpay/views/templates/admin/configure.html.twig` :

` {% for paymentMethod in client.offChain().getPaymentMethods(storeId) %}`
```

### What browser do you use (if useful)?

Tested with Chrome

### Additional information

_No response_

### Are you sure this is a bug report?

- [X] I confirm this is a bug report

### PR DESCRIPTION
**Pull request by BitcoinMitchell**
# Description

Replaced the onchain/offchain calls since they seem to be deprecated (without it being mentioned in the API docs). I've removed t he Smarty variant for now.

- Fixes https://github.com/btcpayserver/prestashop-plugin/issues/169

# Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Refactor (non-breaking change which improves the codebase)

# How Has This Been Tested?

Tested locally with Prestashop Kickstarter and the Testnet BTCPayServer instance (which is 2.0.3).  Also tested on my own store (which is still using BTCPayServer 1.13.5)

**Test Configuration**:
* BTCPay Server version: 1.13.5/2.0.3
* PrestaShop version: 8.0.3/8.1.7

image
image

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have checked my code and corrected any misspellings

---

Test zip: [btcpay v6.3.0.zip](https://github.com/user-attachments/files/17892483/btcpay.v6.3.0.zip)

### CODE REVIEW

**Comment by BitcoinMitchell** [comment]
@deverickapollo could you test the zip attached to this MR?

**Review by ndeet — APPROVED** [review]

File: modules/btcpay/btcpay.php [hunk 1]
```diff
@@ -411,12 +411,6 @@ public function hookPaymentOptions(): array
 				return [];
 			}
 
-			// Prepare smarty
-			$this->context->smarty->assign([
```
Comment (ndeet) [inline modules/btcpay/btcpay.php:415]: You could keep that and the corresponding HTML template at the payment_option.tpl if you just call the global getPaymentMethods and not split it between LN and on-chain, just list the returned payment options? Or do you think it does not need to be there anyway?

Comment (BitcoinMitchell) [reply modules/btcpay/btcpay.php:415]: I was unable to get any text to show. Will fix at a later time. 😁
